export const profileData = [
    {
        id: 1,
        img: "https://cdn.pixabay.com/photo/2022/07/24/23/46/artificial-intelligence-7342613_640.jpg",
        name: "David Smith",
        username: "davidsmith",
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
        link: "/profile/1",
    },
    {
        id: 2,
        img: "https://cdn.pixabay.com/photo/2023/01/05/15/21/technology-7686661_640.jpg",
        name: "Emily Johnson",
        username: "emilyjohnson",
        desc: "Quisque cursus, metus id tincidunt venenatis, lacus erat vehicula sapien.",
        link: "/profile/2",
    },
    {
        id: 3,
        img: "https://cdn.pixabay.com/photo/2023/03/01/12/00/technology-7028236_640.jpg",
        name: "Michael Brown",
        username: "michaelbrown",
        desc: "Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        link: "/profile/3",
    },
    {
        id: 4,
        img: "https://cdn.pixabay.com/photo/2023/05/14/14/31/artificial-intelligence-8008481_640.jpg",
        name: "Sophia Davis",
        username: "sophiadavis",
        desc: "Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
        link: "/profile/4",
    },
    {
        id: 5,
        img: "https://cdn.pixabay.com/photo/2023/07/30/11/44/technology-8225791_640.jpg",
        name: "James Wilson",
        username: "jameswilson",
        desc: "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
        link: "/profile/5",
    },
    {
        id: 6,
        img: "https://cdn.pixabay.com/photo/2023/09/12/15/25/technology-8282647_640.jpg",
        name: "Olivia Martinez",
        username: "oliviamartinez",
        desc: "Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        link: "/profile/6",
    },
    {
        id: 7,
        img: "https://cdn.pixabay.com/photo/2023/10/07/08/45/technology-8359783_640.jpg",
        name: "Liam Garcia",
        username: "liamgarcia",
        desc: "Curabitur pretium tincidunt lacus, sit amet pharetra magna consectetur in.",
        link: "/profile/7",
    },
    {
        id: 8,
        img: "https://cdn.pixabay.com/photo/2023/11/20/09/51/technology-8438123_640.jpg",
        name: "Isabella Lee",
        username: "isabellee",
        desc: "Vestibulum auctor dapibus neque, sit amet fermentum orci auctor sit amet.",
        link: "/profile/8",
    },
]